Lmod Warning:
-------------------------------------------------------------------------------
The following dependent module(s) are not currently loaded: OpenSSL/1.1
(required by: nodejs/16.15.1-GCCcore-11.3.0)
-------------------------------------------------------------------------------



To connect to the notebook type the following command into your local terminal:
ssh -N -J tpelletreaudur@int6-pub.snellius.surf.nl tpelletreaudur@tcn554.local.snellius.surf.nl -L 5124:localhost:5124

After connection is established in your local browser go to the address:
http://localhost:5124
[I 11:44:07.032 NotebookApp] Serving notebooks from local directory: /gpfs/home3/tpelletreaudur/Probing-GNN-representations
[I 11:44:07.032 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 11:44:07.032 NotebookApp] http://localhost:5124/?token=ec2faf53dd2c6d2f87de62d24a8f9479223c685871364617
[I 11:44:07.032 NotebookApp]  or http://127.0.0.1:5124/?token=ec2faf53dd2c6d2f87de62d24a8f9479223c685871364617
[I 11:44:07.032 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:44:07.246 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///gpfs/home3/tpelletreaudur/.local/share/jupyter/runtime/nbserver-932870-open.html
    Or copy and paste one of these URLs:
        http://localhost:5124/?token=ec2faf53dd2c6d2f87de62d24a8f9479223c685871364617
     or http://127.0.0.1:5124/?token=ec2faf53dd2c6d2f87de62d24a8f9479223c685871364617
[I 11:44:59.340 NotebookApp] 302 GET /?token=ec2faf53dd2c6d2f87de62d24a8f9479223c685871364617 (::1) 0.540000ms
/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 11:45:22.468 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[W 11:45:24.337 NotebookApp] Notebook FC_probing_GIN_MDD.ipynb is not trusted
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-8' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/manager.py:75>> is being executed.
[I 11:45:25.723 NotebookApp] Kernel started: 05bf148e-26a4-4de8-aa50-46e15a22fd22, name: python3
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-5' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-14' coro=<MultiKernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/multikernelmanager.py:212>> is being executed.
[I 11:45:26.814 NotebookApp] Kernel started: 5a9c1acd-c13a-4097-8fd1-7b80ec2fc5d3, name: python3
[W 11:45:26.927 NotebookApp] 404 GET /static/components/codemirror/mode/plaintext/plaintext.js?v=20241001114405 (::1) 10.870000ms referer=http://localhost:5124/notebooks/FC_probing_GIN.ipynb
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: be4082f3-e2a0-4c36-9706-ab33006c72c0
[W 11:45:27.637 NotebookApp] 404 GET /static/components/codemirror/mode/plaintext/plaintext.js?v=20241001114405 (::1) 1.250000ms referer=http://localhost:5124/notebooks/FC_probing_GIN_MDD.ipynb
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 28917cb8-7ab2-479a-b74e-993611f3ad90
[I 11:45:39.185 NotebookApp] Kernel interrupted: 05bf148e-26a4-4de8-aa50-46e15a22fd22
[I 11:47:26.245 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 11:47:26.246 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 11:47:27.624 NotebookApp] Saving file at /FC_probing_GIN_MDD.ipynb
[W 11:47:27.625 NotebookApp] Notebook FC_probing_GIN_MDD.ipynb is not trusted
[I 11:49:26.147 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 11:49:26.148 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
Exception in callback <TaskStepMethWrapper object at 0x14cb6a20e380>()
handle: <Handle <TaskStepMethWrapper object at 0x14cb6a20e380>()>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-9' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:842> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-718' coro=<PeriodicCallback._run() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:694]> is being executed.
[I 11:53:26.758 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 11:53:26.759 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 11:55:26.781 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 11:55:26.782 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 11:57:42.895 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 11:57:42.896 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:01:42.790 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:01:42.792 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:05:42.841 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:05:42.844 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:09:42.939 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:09:42.940 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:13:42.910 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:13:42.911 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:17:43.101 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:17:43.104 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:21:42.849 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:21:42.850 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:25:42.854 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:25:42.855 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:27:42.855 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:27:42.928 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:31:42.875 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:31:42.877 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:35:42.886 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:35:42.887 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:39:42.883 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:39:42.884 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:43:42.858 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:43:42.859 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:47:42.902 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:47:42.903 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:51:42.870 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:51:42.871 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:55:42.871 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:55:42.872 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 12:59:42.989 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 12:59:42.990 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:03:42.899 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:03:42.900 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:07:43.036 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:07:43.037 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:11:42.966 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:11:42.968 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:15:43.176 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:15:43.177 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:19:43.281 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:19:43.282 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:23:42.890 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:23:42.891 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:25:42.913 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:25:42.914 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:29:42.943 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:29:42.945 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:33:42.918 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:33:42.919 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:37:42.919 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:37:42.920 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:41:42.945 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:41:42.947 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:45:43.017 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:45:43.018 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:49:42.939 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:49:42.940 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:53:42.937 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:53:42.938 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 13:57:42.973 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 13:57:42.974 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 14:01:43.026 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 14:01:43.027 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 14:05:43.144 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 14:05:43.146 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 14:09:43.016 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 14:09:43.017 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 14:13:43.015 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 14:13:43.016 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
[I 14:15:43.038 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[W 14:15:43.039 NotebookApp] Notebook FC_probing_GIN.ipynb is not trusted
