Lmod Warning:
-------------------------------------------------------------------------------
The following dependent module(s) are not currently loaded: OpenSSL/1.1
(required by: libevent/2.1.12-GCCcore-11.3.0)
-------------------------------------------------------------------------------



GPU available? True
555.42.06
Python 3.10.4
/home/tpelletreaudur/.local/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
Traceback (most recent call last):
  File "/gpfs/home3/tpelletreaudur/Probing-GNN-representations/FC_probing_GIN.py", line 19, in <module>
    gnn.load_model(path="models/"+DATASET+"_"+MODEL+".pt") #, map_location='cpu')
  File "/gpfs/home3/tpelletreaudur/Probing-GNN-representations/models/models_FC.py", line 1459, in load_model
    self.model.load_state_dict(torch.load(path))
  File "/sw/arch/RHEL8/EB_production/2022/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/sw/arch/RHEL8/EB_production/2022/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/sw/arch/RHEL8/EB_production/2022/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/FC_GIN3.pt'

JOB STATISTICS
==============
Job ID: 7702835
Cluster: snellius
User/Group: tpelletreaudur/tpelletreaudur
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:08
CPU Efficiency: 2.12% of 00:06:18 core-walltime
Job Wall-clock time: 00:00:21
Memory Utilized: 2.59 MB
Memory Efficiency: 0.00% of 120.00 GB
